// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUQxBLu-kvxbAPhdazeiZ_UiQQDxxzb1c',
    appId: '1:1097541690824:android:05b043918170837b63ccfd',
    messagingSenderId: '1097541690824',
    projectId: 'maestraelenaapp',
    storageBucket: 'maestraelenaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaOPfs72XL4ePaqzezjUsLcnXe8SEhKeU',
    appId: '1:1097541690824:ios:e2e5fb977da76e9963ccfd',
    messagingSenderId: '1097541690824',
    projectId: 'maestraelenaapp',
    storageBucket: 'maestraelenaapp.appspot.com',
    iosClientId: '1097541690824-95vs4kbdls1d2v8is9iavs5bpbvjl8bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.maestraelenaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaOPfs72XL4ePaqzezjUsLcnXe8SEhKeU',
    appId: '1:1097541690824:ios:e2e5fb977da76e9963ccfd',
    messagingSenderId: '1097541690824',
    projectId: 'maestraelenaapp',
    storageBucket: 'maestraelenaapp.appspot.com',
    iosClientId: '1097541690824-95vs4kbdls1d2v8is9iavs5bpbvjl8bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.maestraelenaApp',
  );
}
